services:

  app:
    build: .
    container_name: rate-limiter-app
    ports:
      - "8080:8080"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - rate-limiter-net
    restart: on-failure

  redis:
    image: redis:7.2.4-alpine
    container_name: rate-limiter-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - rate-limiter-net
    volumes:
      - redis-data:/data

  prometheus:
    image: prom/prometheus:v2.51.2
    container_name: rate-limiter-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./docker/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks:
      - rate-limiter-net
    depends_on:
      - app

networks:
  rate-limiter-net:
    driver: bridge

volumes:
  redis-data:
